### PR TITLE
go-sbot: Panic less in main()

### PR DESCRIPTION
**Pull request by freight-stack**
Copy the pattern from docker's cli to log and return errors without panicing.

### CODE REVIEW

**Comment by freight-stack** [comment]
Hi @cryptix do you like this patch updated?

**Comment by cryptix** [comment]
@freight-stack ah, sorry! if you find the time, sure yes please! this would be cool to have.

**Comment by freight-stack** [comment]
Updated @cryptix

**Comment by cryptix** [comment]
Thanks a lot, @freight-stack!

**Pull request merged**
