### PR TITLE
Make connection late in sbotcli

### PR DESCRIPTION
**Pull request by freight-stack**
Connect to the ssb server as late as possible in order to avoid side effects.

### CODE REVIEW

**Comment by cryptix** [comment]
I guess this is supposed to fix what you described in #28? I can't merge this without understanding what is acting up. Sorry for the wrong error message.

**Comment by freight-stack** [comment]
That is ok.  It is not a fix for #28, but it is similar.  It stops the '-help' from being printed when the connect command fails.

**Comment by freight-stack** [comment]
Hi @cryptix, how could I help support review of these changes?  Would you like more problem description or tests?

**Comment by freight-stack** [comment]
"Main thing I don’t want to break right now is being able to use TCP and unixsock connections."

I can add testing for the CLI in another PR.  It can be used for proving quality for this and others.  Up for that?

**Comment by cryptix** [comment]
Sure!

**Comment by cryptix** [comment]
Thanks! I really like the idea of this change. I know the --help can be confusing.  I will check this out tomorrow and check if it works with my private tools.

**Comment by freight-stack** [comment]
Hi @cryptix is patch still valid?  Would you like update?

**Comment by cryptix** [comment]
Merged in c4ab8d0fce5a8e7829f169330c0b73832e11d1ef

Thanks a lot!

**Pull request closed without merging**
