### PR TITLE
WIP: start work on key value multilog

### PR DESCRIPTION
**Pull request by keks**
this is the start of a generic indexing thing.

### CODE REVIEW

**Comment by keks** [comment]
review not urgent, more of a "what do you think of this approach?"

**Comment by cryptix** [comment]
uhm.. not sure what the goal is for this. This just indexes all first level fields right?

**Comment by keks** [comment]
Yes. I plan to add a stream merger and index query scheduler such that it's easy to make queries like "all post messages in channel vegan-junkfood by keks".

Am 24. Juni 2019 09:29:44 MESZ schrieb Henry <notifications@github.com>:
>uhm.. not sure what the goal is for this. This just indexes all first
>level fields right?

-- 
Sent from mobile.

**Comment by keks** [comment]
basic tests pass now.

TODO:
- more tests
- comments/docs
- query intersection thing

**Pull request closed without merging**
